### ISSUE TITLE
Compile with Scala 2.12.4

### ISSUE THREAD

**Issue by Ma27** [Ma27/rediscala#5]
When trying to bump the Scala version in our SBT build to `2.12.4` the following happens:

```
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/ma27/Projects/rediscala/project
[info] Loading settings from build.sbt,version.sbt ...
[info] Set current project to rediscala (in build file:/home/ma27/Projects/rediscala/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating ...
[info] Done updating.
[info] Compiling 51 Scala sources and 1 Java source to /home/ma27/Projects/rediscala/target/scala-2.12/classes ...
[error] /home/ma27/Projects/rediscala/src/main/scala/redis/api/Keys.scala:105:24: case classes should have a non-implicit parameter list; adapting to 'case class Randomkey()(...)'
[error] case class Randomkey[R](implicit deserializerR: ByteStringDeserializer[R]) extends RedisCommandBulkOptionByteString[R] {
[error]                        ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed Mar 17, 2018 7:02:04 PM
```

We have to investigate if that's a compiler bug or an intentional change and fix our code accordingly.

**Comment by herzrasen** [comment]
I can take care of this one

**Comment by herzrasen** [comment]
@Ma27 I will push my changes when you merged your #4 back to master.

**Comment by Ma27** [comment]
@herzrasen I just merged it for now. I'll try to have a look at this, in case I have sufficient time, I'll build a release tonight :)
